fix(rp2040): fix subs registers wrong overflow handling
wokwi/rp2040js pull request #47
Opened 2021-05-28 18:29 UTC by Turro75

close #46

2021-05-28 21:09 UTC, urish requested changes
Thanks Valerio! It's very helpful that you find all these sneaky bugs.

Any chance you can add test cases for the SBCS / CMP fixes as well?

2021-05-28 21:09 UTC, urish commented on src/rp2040.ts
> +      this.N = !!(result & 0x80000000);
Why not `result < 0`? I think it's a bit easier to read it that way (and we also calculate `N` like that in other places, such as the `CMP` instruction

2021-05-28 22:23 UTC, urish commented on src/instructions.spec.ts
> +      expect(registers2.r0).toEqual(0x55);
can you please explain this change?

2021-05-28 22:23 UTC, urish commented on src/instructions.spec.ts
> +    await cpu.setRegisters({
good catch!

2021-05-28 22:31 UTC, urish commented
Also, can you move the STR fix into a different pull request (different branch), together with the test case from #43? 

I think a bunch of other instructions have the same issue as well: STRH, STRB, LDR, LDRB, LDRH, LDRS, LDRSB

We can skip creating tests for each one of them, but since we already have the test case for `STR`, let's at least include it

2021-05-30 13:25 UTC, Turro75 commented
I'm gonna reworking it

2021-05-30 13:25 UTC, closed without merging

2021-05-30 14:37 UTC, urish commented
Thank you!